project: 
  type: website
  
  
website: 
  favicon: images/favicon.ico
  page-navigation: true
  title: "A Biomedical Visualization Atlas" 
  site-url: "http://genaimed.org/Bizard/" 
  repo-url: https://github.com/DrRobinLuo/Bizard
  repo-actions:
    - source
    - issue
  
  page-footer:
    left: "&copy; CC-By Peng Lab, 2024-2025. All rights reserved."
    right: "This page is built with [Quarto](https://quarto.org/)."
    center: |
      <a href='https://clustrmaps.com/site/1c4xe'  title='Visit tracker'><img src='//clustrmaps.com/map_v2.png?cl=ffffff&w=a&t=n&d=VK6_Uhjas4vA0CDps3EFeB0Fotb8hU50SYT4Fcq5nUI&co=91c5eb&ct=000000'/></a>
    
  sidebar:
    logo: "images/Bizard_logo.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/DrRobinLuo/Bizard
        text: "Bizard GitHub website"
      - icon: twitter
        href: https://x.com/PengL_Robin
        text: "Peng Lab Twitter"
      - icon: translate       

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Graph Gallery"
        href: Graph-Gallery.qmd
      - section: "Distribution"
        contents: 
          - text: "Violin Plot"
            href: Distribution/ViolinPlot.qmd
          - text: "Density Plot"
            href: Distribution/Density.qmd
          - text: "Histogram"
            href: Distribution/Histogram.qmd
          - text: "Box Plot"
            href: Distribution/BoxPlot.qmd
          - text: "Ridgeline Plot"
            href: Distribution/Ridgeline.qmd
      - section: "Correlation"
        contents: 
          - text: "Scatter Plot"
            href: Correlation/Scatter.qmd
          - text: "Heatmap"
            href: Correlation/Heatmap.qmd
          - text: "Correlogram"
            href: Correlation/Correlogram.qmd
          - text: "Bubble Plot"
            href: Correlation/Bubble.qmd
          - text: "Connected Scatter"
            href: Correlation/ConnectedScatter.qmd
          - text: "2D Density"
            href: Correlation/Density2D.qmd
      - text: "About Us"
        href: About.qmd
        

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto
  
  
comments:
  giscus:
    repo: "DrRobinLuo/Bizard"
    repo-id: "R_kgDONWVY7Q"
    category: "Announcements"
    category-id: "DIC_kwDONWVY7c4ClcJT"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "top"
    theme: "preferred_color_scheme"
    loading: "lazy"
