# ref: https://quarto.org/docs/publishing/github-pages.html#example-knitr-with-renv
# https://github.com/quarto-dev/quarto-actions/tree/main/render
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: Quarto Render Hiplot dirs

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
          path: Hiplot # By default, the current working dir is used i.e `quarto render .`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

